"""initial_pg_schema

Revision ID: 4d6ae351e623
Revises: 
Create Date: 2026-05-12 18:50:32.457086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6ae351e623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_collected_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collected_user', 'agent_collected_info', ['user_id', 'collected_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agent2_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auth_user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('audio_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['auth_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent2_msg_user_created', 'agent2_messages', ['auth_user_id', 'created_at'], unique=False)
    op.create_index('idx_agent2_msg_user_role', 'agent2_messages', ['auth_user_id', 'role'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auth_user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('audio_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['auth_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_msg_user_created', 'agent_messages', ['auth_user_id', 'created_at'], unique=False)
    op.create_index('idx_agent_msg_user_role', 'agent_messages', ['auth_user_id', 'role'], unique=False)
    op.create_table('agent_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auth_user_id', sa.String(), nullable=False),
    sa.Column('agent_label', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact_jours', sa.Float(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('target_so_hint', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('responded_at', sa.String(), nullable=True),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['auth_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_proposals_user', 'agent_proposals', ['auth_user_id', 'statut'], unique=False)
    op.create_table('profil_utilisateur',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('profession', sa.String(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('situation_familiale', sa.String(), nullable=False),
    sa.Column('revenu_annuel', sa.Float(), nullable=False),
    sa.Column('patrimoine_estime', sa.Float(), nullable=False),
    sa.Column('charges_mensuelles', sa.Float(), nullable=False),
    sa.Column('objectif_financier', sa.Float(), nullable=True),
    sa.Column('heures_travail', sa.Float(), nullable=True),
    sa.Column('heures_sommeil', sa.Float(), nullable=True),
    sa.Column('heures_loisirs', sa.Float(), nullable=True),
    sa.Column('heures_transport', sa.Float(), nullable=True),
    sa.Column('heures_objectif', sa.Float(), nullable=True),
    sa.Column('niveau_sante', sa.Integer(), nullable=True),
    sa.Column('niveau_stress', sa.Integer(), nullable=True),
    sa.Column('niveau_energie', sa.Integer(), nullable=True),
    sa.Column('niveau_bonheur', sa.Integer(), nullable=True),
    sa.Column('competences', sa.Text(), nullable=True),
    sa.Column('diplomes', sa.Text(), nullable=True),
    sa.Column('langues', sa.Text(), nullable=True),
    sa.Column('objectif_description', sa.Text(), nullable=True),
    sa.Column('objectif_categorie', sa.String(), nullable=True),
    sa.Column('objectif_deadline', sa.String(), nullable=True),
    sa.Column('objectif_probabilite_base', sa.Float(), nullable=True),
    sa.Column('objectif_probabilite_calculee', sa.Float(), nullable=True),
    sa.Column('probabilite_actuelle', sa.Float(), nullable=True),
    sa.Column('auth_user_id', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('objectif_modifie_le', sa.String(), nullable=True),
    sa.Column('phrase_personnalite', sa.Text(), nullable=True),
    sa.Column('temps_initial_jours', sa.Integer(), nullable=True),
    sa.Column('temps_gagne_jours', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('cree_le', sa.String(), nullable=False),
    sa.Column('mis_a_jour_le', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profil_utilisateur_auth_user_id'), 'profil_utilisateur', ['auth_user_id'], unique=False)
    op.create_table('bilans_quotidiens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('niveau_sante', sa.Integer(), nullable=True),
    sa.Column('niveau_stress', sa.Integer(), nullable=True),
    sa.Column('niveau_energie', sa.Integer(), nullable=True),
    sa.Column('niveau_bonheur', sa.Integer(), nullable=True),
    sa.Column('heures_travail', sa.Float(), nullable=True),
    sa.Column('heures_sommeil', sa.Float(), nullable=True),
    sa.Column('heures_loisirs', sa.Float(), nullable=True),
    sa.Column('heures_transport', sa.Float(), nullable=True),
    sa.Column('heures_objectif', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profil_utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_bilan_user_date')
    )
    op.create_index('idx_bilans_user_date', 'bilans_quotidiens', ['user_id', 'date'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('probabilite_avant', sa.Float(), nullable=False),
    sa.Column('option_choisie_id', sa.String(), nullable=True),
    sa.Column('probabilite_apres', sa.Float(), nullable=True),
    sa.Column('action_agent_json', sa.Text(), nullable=True),
    sa.Column('temps_gagne_avant', sa.Float(), nullable=True),
    sa.Column('temps_gagne_apres', sa.Float(), nullable=True),
    sa.Column('sous_objectif_id', sa.String(), nullable=True),
    sa.Column('sous_objectif_impacte', sa.String(), nullable=True),
    sa.Column('impact_sous_objectif', sa.Float(), nullable=True),
    sa.Column('cree_le', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profil_utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decisions_user_cree', 'decisions', ['user_id', 'cree_le'], unique=False)
    op.create_index(op.f('ix_decisions_sous_objectif_id'), 'decisions', ['sous_objectif_id'], unique=False)
    op.create_index(op.f('ix_decisions_user_id'), 'decisions', ['user_id'], unique=False)
    op.create_table('sous_objectifs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('progression', sa.Float(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('temps_estime', sa.Float(), nullable=True),
    sa.Column('cree_le', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profil_utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_so_user_ordre', 'sous_objectifs', ['user_id', 'ordre'], unique=False)
    op.create_table('taches_quotidiennes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('taches_json', sa.Text(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=True),
    sa.Column('cree_le', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profil_utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_taches_user_date')
    )
    op.create_index('idx_taches_user_date', 'taches_quotidiennes', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_taches_user_date', table_name='taches_quotidiennes')
    op.drop_table('taches_quotidiennes')
    op.drop_index('idx_so_user_ordre', table_name='sous_objectifs')
    op.drop_table('sous_objectifs')
    op.drop_index(op.f('ix_decisions_user_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_sous_objectif_id'), table_name='decisions')
    op.drop_index('idx_decisions_user_cree', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('idx_bilans_user_date', table_name='bilans_quotidiens')
    op.drop_table('bilans_quotidiens')
    op.drop_index(op.f('ix_profil_utilisateur_auth_user_id'), table_name='profil_utilisateur')
    op.drop_table('profil_utilisateur')
    op.drop_index('idx_agent_proposals_user', table_name='agent_proposals')
    op.drop_table('agent_proposals')
    op.drop_index('idx_agent_msg_user_role', table_name='agent_messages')
    op.drop_index('idx_agent_msg_user_created', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('idx_agent2_msg_user_role', table_name='agent2_messages')
    op.drop_index('idx_agent2_msg_user_created', table_name='agent2_messages')
    op.drop_table('agent2_messages')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_collected_user', table_name='agent_collected_info')
    op.drop_table('agent_collected_info')
    # ### end Alembic commands ###
