import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from 'react'

import frJson from './locales/fr.json'

type Translations = Record<string, unknown>

interface LanguageCtx {
  locale: string
  setLocale: (code: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageCtx>({
  locale: 'fr',
  setLocale: () => {},
  t: (k) => k,
})

export const useT = () => useContext(LanguageContext).t
export const useLocale = () => {
  const ctx = useContext(LanguageContext)
  return { locale: ctx.locale, setLocale: ctx.setLocale }
}

// Lookup dot-notated key in nested object
function lookup(obj: Translations, key: string): string {
  const parts = key.split('.')
  let cur: unknown = obj
  for (const p of parts) {
    if (cur && typeof cur === 'object' && p in (cur as Record<string, unknown>)) {
      cur = (cur as Record<string, unknown>)[p]
    } else {
      return key // fallback: return the key itself
    }
  }
  return typeof cur === 'string' ? cur : key
}

// Dynamic import of locale files (fr and en have full JSON files)
const localeLoaders: Record<string, () => Promise<{ default: Translations }>> = {
  fr: () => import('./locales/fr.json'),
  en: () => import('./locales/en.json'),
  'en-US': () => import('./locales/en.json'),
  es: () => import('./locales/es.json'),
  de: () => import('./locales/de.json'),
  pt: () => import('./locales/pt.json'),
  ar: () => import('./locales/ar.json'),
  zh: () => import('./locales/zh.json'),
  it: () => import('./locales/it.json'),
  ru: () => import('./locales/ru.json'),
  ja: () => import('./locales/ja.json'),
  ko: () => import('./locales/ko.json'),
  tr: () => import('./locales/tr.json'),
  hi: () => import('./locales/hi.json'),
  nl: () => import('./locales/nl.json'),
  pl: () => import('./locales/pl.json'),
  sv: () => import('./locales/sv.json'),
  th: () => import('./locales/th.json'),
  vi: () => import('./locales/vi.json'),
  id: () => import('./locales/id.json'),
  el: () => import('./locales/el.json'),
  ro: () => import('./locales/ro.json'),
  uk: () => import('./locales/uk.json'),
  fi: () => import('./locales/fi.json'),
  cs: () => import('./locales/cs.json'),
  hu: () => import('./locales/hu.json'),
  da: () => import('./locales/da.json'),
  no: () => import('./locales/no.json'),
  he: () => import('./locales/he.json'),
  ms: () => import('./locales/ms.json'),
  tl: () => import('./locales/tl.json'),
  sw: () => import('./locales/sw.json'),
  fa: () => import('./locales/fa.json'),
  af: () => import('./locales/af.json'),
  sq: () => import('./locales/sq.json'),
  am: () => import('./locales/am.json'),
  hy: () => import('./locales/hy.json'),
  az: () => import('./locales/az.json'),
  eu: () => import('./locales/eu.json'),
  bn: () => import('./locales/bn.json'),
  bs: () => import('./locales/bs.json'),
  bg: () => import('./locales/bg.json'),
  my: () => import('./locales/my.json'),
  ca: () => import('./locales/ca.json'),
  'zh-TW': () => import('./locales/zh-TW.json'),
  hr: () => import('./locales/hr.json'),
  et: () => import('./locales/et.json'),
  gl: () => import('./locales/gl.json'),
  ka: () => import('./locales/ka.json'),
  gu: () => import('./locales/gu.json'),
  ha: () => import('./locales/ha.json'),
  is: () => import('./locales/is.json'),
  ig: () => import('./locales/ig.json'),
  ga: () => import('./locales/ga.json'),
  kn: () => import('./locales/kn.json'),
  kk: () => import('./locales/kk.json'),
  km: () => import('./locales/km.json'),
  la: () => import('./locales/la.json'),
  lv: () => import('./locales/lv.json'),
  lt: () => import('./locales/lt.json'),
  lo: () => import('./locales/lo.json'),
  mk: () => import('./locales/mk.json'),
  ml: () => import('./locales/ml.json'),
  mt: () => import('./locales/mt.json'),
  mr: () => import('./locales/mr.json'),
  mn: () => import('./locales/mn.json'),
  ne: () => import('./locales/ne.json'),
  pa: () => import('./locales/pa.json'),
  sr: () => import('./locales/sr.json'),
  si: () => import('./locales/si.json'),
  sk: () => import('./locales/sk.json'),
  sl: () => import('./locales/sl.json'),
  ta: () => import('./locales/ta.json'),
  te: () => import('./locales/te.json'),
  ur: () => import('./locales/ur.json'),
  uz: () => import('./locales/uz.json'),
  cy: () => import('./locales/cy.json'),
  xh: () => import('./locales/xh.json'),
  yo: () => import('./locales/yo.json'),
  zu: () => import('./locales/zu.json'),
}

// ── Traductions embarquees pour les principales langues ──────────────────────
// Couvrent nav + settings + lock (les cles les plus visibles de l'UI)
const embeddedTranslations: Record<string, Translations> = {
  es: {"nav":{"dashboard":"Panel de control","analyser":"Analizar una eleccion","statistiques":"Estadisticas","parametres":"Ajustes","parametres_desc":"Idioma, seguridad, archivos","aide":"Ayuda y recursos","aide_desc":"Proximamente","service":"Servicio al cliente","service_desc":"Chatea con nuestro asistente","profil_edit":"Editar mi perfil","profil_create":"Crear mi perfil","profil_edit_desc":"Actualiza tu informacion","profil_create_desc":"Comienza tu recorrido"},"settings":{"title":"Ajustes","subtitle":"Personaliza tu experiencia Sylea","profil":"Mi perfil","profil_desc":"Consulta tu informacion personal","langue":"Idioma","langue_desc":"Elige el idioma de la aplicacion","securite":"Seguridad","securite_desc":"Protege tus datos personales","archives":"Archivo de decisiones","archives_desc":"Encuentra todas tus decisiones pasadas","identite":"Identidad","objectif":"Objetivo de vida","competences":"Competencias","diplomes":"Diplomas","langues":"Idiomas","bien_etre":"Bienestar","repartition_temps":"Distribucion del tiempo","genre":"Genero","nom":"Nombre","age":"Edad","profession":"Profesion","ville":"Ciudad","situation":"Estado familiar","categorie":"Categoria","deadline":"Fecha limite","probabilite":"Probabilidad actual","sante":"Salud","stress":"Estres","energie":"Energia","bonheur":"Felicidad","travail":"Trabajo","sommeil":"Sueno","loisirs":"Ocio","transport":"Transporte","objectif_h":"Objetivo","h_jour":"h/dia","ans":"anos","rechercher":"Buscar una decision...","tri_recent":"Mas recientes","tri_ancien":"Mas antiguas","tri_impact":"Por impacto","aucune_decision":"Ninguna decision encontrada","impact":"Impacto","choix":"Eleccion","date":"Fecha","page":"Pagina","sur":"de","securite_niveau":"Nivel de seguridad","aucun_verrou":"Sin bloqueo","mot_de_passe":"Contrasena","schema":"Patron de bloqueo","creer_mdp":"Crear contrasena","creer_schema":"Dibujar patron","confirmer_mdp":"Confirmar contrasena","confirmer_schema":"Confirmar patron","supprimer_verrou":"Eliminar bloqueo","verrou_actif":"Bloqueo activo","mdp_placeholder":"Ingresa tu contrasena...","mdp_confirmer_placeholder":"Confirma tu contrasena...","mdp_mismatch":"Las contrasenas no coinciden","mdp_trop_court":"Minimo 4 caracteres","schema_trop_court":"Conecta al menos 4 puntos","verrou_cree":"Bloqueo creado exitosamente","verrou_supprime":"Bloqueo eliminado","langue_changee":"Idioma cambiado","rechercher_langue":"Buscar un idioma...","non_defini":"No definido","non_renseigne":"No proporcionado"},"lock":{"titre":"Sylea esta bloqueada","mdp_placeholder":"Ingresa tu contrasena...","schema_instruction":"Dibuja tu patron","erreur":"Contrasena o patron incorrecto","deverrouiller":"Desbloquear"}},
  de: {"nav":{"dashboard":"Ubersicht","analyser":"Entscheidung analysieren","statistiques":"Statistiken","parametres":"Einstellungen","parametres_desc":"Sprache, Sicherheit, Archiv","aide":"Hilfe & Ressourcen","aide_desc":"Demnachst verfugbar","service":"Kundendienst","service_desc":"Mit unserem Assistenten chatten","profil_edit":"Profil bearbeiten","profil_create":"Profil erstellen","profil_edit_desc":"Informationen aktualisieren","profil_create_desc":"Starte deine Reise"},"settings":{"title":"Einstellungen","subtitle":"Passe deine Sylea-Erfahrung an","profil":"Mein Profil","profil_desc":"Personliche Informationen anzeigen","langue":"Sprache","langue_desc":"Wahle die App-Sprache","securite":"Sicherheit","securite_desc":"Schutze deine personlichen Daten","archives":"Entscheidungsarchiv","archives_desc":"Finde alle vergangenen Entscheidungen","identite":"Identitat","objectif":"Lebensziel","competences":"Kompetenzen","diplomes":"Abschlusse","langues":"Sprachen","bien_etre":"Wohlbefinden","repartition_temps":"Zeitverteilung","genre":"Geschlecht","nom":"Name","age":"Alter","profession":"Beruf","ville":"Stadt","situation":"Familienstatus","categorie":"Kategorie","deadline":"Frist","probabilite":"Aktuelle Wahrscheinlichkeit","sante":"Gesundheit","stress":"Stress","energie":"Energie","bonheur":"Gluck","travail":"Arbeit","sommeil":"Schlaf","loisirs":"Freizeit","transport":"Transport","objectif_h":"Ziel","h_jour":"Std/Tag","ans":"Jahre","rechercher":"Entscheidung suchen...","tri_recent":"Neueste","tri_ancien":"Alteste","tri_impact":"Nach Auswirkung","aucune_decision":"Keine Entscheidung gefunden","impact":"Auswirkung","choix":"Wahl","date":"Datum","page":"Seite","sur":"von","securite_niveau":"Sicherheitsstufe","aucun_verrou":"Keine Sperre","mot_de_passe":"Passwort","schema":"Entsperrmuster","creer_mdp":"Passwort erstellen","creer_schema":"Muster zeichnen","confirmer_mdp":"Passwort bestatigen","confirmer_schema":"Muster bestatigen","supprimer_verrou":"Sperre entfernen","verrou_actif":"Sperre aktiv","mdp_placeholder":"Passwort eingeben...","mdp_confirmer_placeholder":"Passwort bestatigen...","mdp_mismatch":"Passworter stimmen nicht uberein","mdp_trop_court":"Mindestens 4 Zeichen","schema_trop_court":"Mindestens 4 Punkte verbinden","verrou_cree":"Sperre erfolgreich erstellt","verrou_supprime":"Sperre entfernt","langue_changee":"Sprache geandert","rechercher_langue":"Sprache suchen...","non_defini":"Nicht definiert","non_renseigne":"Nicht angegeben"},"lock":{"titre":"Sylea ist gesperrt","mdp_placeholder":"Passwort eingeben...","schema_instruction":"Zeichne dein Muster","erreur":"Falsches Passwort oder Muster","deverrouiller":"Entsperren"}},
  pt: {"nav":{"dashboard":"Painel","analyser":"Analisar uma escolha","statistiques":"Estatisticas","parametres":"Configuracoes","parametres_desc":"Idioma, seguranca, arquivos","aide":"Ajuda e recursos","aide_desc":"Em breve","service":"Atendimento","service_desc":"Converse com nosso assistente","profil_edit":"Editar meu perfil","profil_create":"Criar meu perfil","profil_edit_desc":"Atualizar informacoes","profil_create_desc":"Comece sua jornada"},"settings":{"title":"Configuracoes","subtitle":"Personalize sua experiencia Sylea","profil":"Meu perfil","profil_desc":"Veja suas informacoes pessoais","langue":"Idioma","langue_desc":"Escolha o idioma do aplicativo","securite":"Seguranca","securite_desc":"Proteja seus dados pessoais","archives":"Arquivo de decisoes","archives_desc":"Encontre todas as suas decisoes passadas","identite":"Identidade","objectif":"Objetivo de vida","competences":"Competencias","diplomes":"Diplomas","langues":"Idiomas","bien_etre":"Bem-estar","repartition_temps":"Distribuicao do tempo","genre":"Genero","nom":"Nome","age":"Idade","profession":"Profissao","ville":"Cidade","situation":"Estado familiar","categorie":"Categoria","deadline":"Prazo","probabilite":"Probabilidade atual","sante":"Saude","stress":"Estresse","energie":"Energia","bonheur":"Felicidade","travail":"Trabalho","sommeil":"Sono","loisirs":"Lazer","transport":"Transporte","objectif_h":"Objetivo","h_jour":"h/dia","ans":"anos","rechercher":"Buscar uma decisao...","tri_recent":"Mais recentes","tri_ancien":"Mais antigas","tri_impact":"Por impacto","aucune_decision":"Nenhuma decisao encontrada","impact":"Impacto","choix":"Escolha","date":"Data","page":"Pagina","sur":"de","securite_niveau":"Nivel de seguranca","aucun_verrou":"Sem bloqueio","mot_de_passe":"Senha","schema":"Padrao de desbloqueio","creer_mdp":"Criar senha","creer_schema":"Desenhar padrao","confirmer_mdp":"Confirmar senha","confirmer_schema":"Confirmar padrao","supprimer_verrou":"Remover bloqueio","verrou_actif":"Bloqueio ativo","mdp_placeholder":"Digite sua senha...","mdp_confirmer_placeholder":"Confirme sua senha...","mdp_mismatch":"As senhas nao coincidem","mdp_trop_court":"Minimo 4 caracteres","schema_trop_court":"Conecte pelo menos 4 pontos","verrou_cree":"Bloqueio criado com sucesso","verrou_supprime":"Bloqueio removido","langue_changee":"Idioma alterado","rechercher_langue":"Buscar um idioma...","non_defini":"Nao definido","non_renseigne":"Nao informado"},"lock":{"titre":"Sylea esta bloqueada","mdp_placeholder":"Digite sua senha...","schema_instruction":"Desenhe seu padrao","erreur":"Senha ou padrao incorreto","deverrouiller":"Desbloquear"}},
  it: {"nav":{"dashboard":"Pannello","analyser":"Analizzare una scelta","statistiques":"Statistiche","parametres":"Impostazioni","parametres_desc":"Lingua, sicurezza, archivi","aide":"Aiuto e risorse","aide_desc":"Prossimamente","service":"Servizio clienti","service_desc":"Chatta con il nostro assistente","profil_edit":"Modifica profilo","profil_create":"Crea profilo","profil_edit_desc":"Aggiorna le informazioni","profil_create_desc":"Inizia il tuo percorso"},"settings":{"title":"Impostazioni","subtitle":"Personalizza la tua esperienza Sylea","profil":"Il mio profilo","profil_desc":"Visualizza le informazioni personali","langue":"Lingua","langue_desc":"Scegli la lingua dell'app","securite":"Sicurezza","securite_desc":"Proteggi i tuoi dati personali","archives":"Archivio decisioni","archives_desc":"Trova tutte le decisioni passate","identite":"Identita","objectif":"Obiettivo di vita","competences":"Competenze","diplomes":"Diplomi","langues":"Lingue","bien_etre":"Benessere","repartition_temps":"Distribuzione del tempo","genre":"Genere","nom":"Nome","age":"Eta","profession":"Professione","ville":"Citta","situation":"Stato familiare","categorie":"Categoria","deadline":"Scadenza","probabilite":"Probabilita attuale","sante":"Salute","stress":"Stress","energie":"Energia","bonheur":"Felicita","travail":"Lavoro","sommeil":"Sonno","loisirs":"Tempo libero","transport":"Trasporto","objectif_h":"Obiettivo","h_jour":"ore/giorno","ans":"anni","rechercher":"Cerca una decisione...","tri_recent":"Piu recenti","tri_ancien":"Piu vecchie","tri_impact":"Per impatto","aucune_decision":"Nessuna decisione trovata","impact":"Impatto","choix":"Scelta","date":"Data","page":"Pagina","sur":"di","securite_niveau":"Livello sicurezza","aucun_verrou":"Nessun blocco","mot_de_passe":"Password","schema":"Segno di sblocco","creer_mdp":"Crea password","creer_schema":"Disegna segno","confirmer_mdp":"Conferma password","confirmer_schema":"Conferma segno","supprimer_verrou":"Rimuovi blocco","verrou_actif":"Blocco attivo","mdp_placeholder":"Inserisci password...","mdp_confirmer_placeholder":"Conferma password...","mdp_mismatch":"Le password non corrispondono","mdp_trop_court":"Minimo 4 caratteri","schema_trop_court":"Collega almeno 4 punti","verrou_cree":"Blocco creato con successo","verrou_supprime":"Blocco rimosso","langue_changee":"Lingua cambiata","rechercher_langue":"Cerca una lingua...","non_defini":"Non definito","non_renseigne":"Non fornito"},"lock":{"titre":"Sylea e bloccata","mdp_placeholder":"Inserisci password...","schema_instruction":"Disegna il tuo segno","erreur":"Password o segno errato","deverrouiller":"Sblocca"}},
  ru: {"nav":{"dashboard":"Панель управления","analyser":"Анализ выбора","statistiques":"Статистика","parametres":"Настройки","parametres_desc":"Язык, безопасность, архив","aide":"Помощь и ресурсы","aide_desc":"Скоро будет","service":"Служба поддержки","service_desc":"Чат с нашим ассистентом","profil_edit":"Редактировать профиль","profil_create":"Создать профиль","profil_edit_desc":"Обновить информацию","profil_create_desc":"Начните свой путь"},"settings":{"title":"Настройки","subtitle":"Настройте Sylea под себя","profil":"Мой профиль","profil_desc":"Просмотр личной информации","langue":"Язык","langue_desc":"Выберите язык приложения","securite":"Безопасность","securite_desc":"Защитите свои данные","archives":"Архив решений","archives_desc":"Найдите все прошлые решения","identite":"Личность","objectif":"Жизненная цель","competences":"Навыки","diplomes":"Дипломы","langues":"Языки","bien_etre":"Благополучие","repartition_temps":"Распределение времени","genre":"Пол","nom":"Имя","age":"Возраст","profession":"Профессия","ville":"Город","situation":"Семейное положение","categorie":"Категория","deadline":"Срок","probabilite":"Текущая вероятность","sante":"Здоровье","stress":"Стресс","energie":"Энергия","bonheur":"Счастье","travail":"Работа","sommeil":"Сон","loisirs":"Досуг","transport":"Транспорт","objectif_h":"Цель","h_jour":"ч/день","ans":"лет","rechercher":"Поиск решения...","tri_recent":"Новые","tri_ancien":"Старые","tri_impact":"По влиянию","aucune_decision":"Решения не найдены","impact":"Влияние","choix":"Выбор","date":"Дата","page":"Страница","sur":"из","securite_niveau":"Уровень безопасности","aucun_verrou":"Нет блокировки","mot_de_passe":"Пароль","schema":"Графический ключ","creer_mdp":"Создать пароль","creer_schema":"Нарисовать ключ","confirmer_mdp":"Подтвердить пароль","confirmer_schema":"Подтвердить ключ","supprimer_verrou":"Удалить блокировку","verrou_actif":"Блокировка активна","mdp_placeholder":"Введите пароль...","mdp_confirmer_placeholder":"Подтвердите пароль...","mdp_mismatch":"Пароли не совпадают","mdp_trop_court":"Минимум 4 символа","schema_trop_court":"Соедините минимум 4 точки","verrou_cree":"Блокировка создана","verrou_supprime":"Блокировка удалена","langue_changee":"Язык изменён","rechercher_langue":"Поиск языка...","non_defini":"Не определено","non_renseigne":"Не указано"},"lock":{"titre":"Sylea заблокирована","mdp_placeholder":"Введите пароль...","schema_instruction":"Нарисуйте ключ","erreur":"Неверный пароль или ключ","deverrouiller":"Разблокировать"}},
  ja: {"nav":{"dashboard":"ダッシュボード","analyser":"選択を分析","statistiques":"統計","parametres":"設定","parametres_desc":"言語、セキュリティ、アーカイブ","aide":"ヘルプ","aide_desc":"近日公開","service":"カスタマーサービス","service_desc":"アシスタントとチャット","profil_edit":"プロフィール編集","profil_create":"プロフィール作成","profil_edit_desc":"情報を更新","profil_create_desc":"始めましょう"},"settings":{"title":"設定","subtitle":"Syleaの体験をカスタマイズ","profil":"マイプロフィール","profil_desc":"個人情報を表示","langue":"言語","langue_desc":"アプリの言語を選択","securite":"セキュリティ","securite_desc":"個人データを保護","archives":"決定アーカイブ","archives_desc":"過去の決定を検索","identite":"身元","objectif":"人生の目標","competences":"スキル","diplomes":"学位","langues":"言語","bien_etre":"幸福度","repartition_temps":"時間配分","genre":"性別","nom":"名前","age":"年齢","profession":"職業","ville":"都市","situation":"家族状況","categorie":"カテゴリ","deadline":"期限","probabilite":"現在の確率","sante":"健康","stress":"ストレス","energie":"エネルギー","bonheur":"幸福","travail":"仕事","sommeil":"睡眠","loisirs":"余暇","transport":"交通","objectif_h":"目標","h_jour":"時間/日","ans":"歳","rechercher":"決定を検索...","tri_recent":"最新","tri_ancien":"最古","tri_impact":"影響順","aucune_decision":"決定が見つかりません","impact":"影響","choix":"選択","date":"日付","page":"ページ","sur":"の","securite_niveau":"セキュリティレベル","aucun_verrou":"ロックなし","mot_de_passe":"パスワード","schema":"パターンロック","creer_mdp":"パスワード作成","creer_schema":"パターン描画","confirmer_mdp":"パスワード確認","confirmer_schema":"パターン確認","supprimer_verrou":"ロック解除","verrou_actif":"ロック有効","mdp_placeholder":"パスワードを入力...","mdp_confirmer_placeholder":"パスワードを確認...","mdp_mismatch":"パスワードが一致しません","mdp_trop_court":"4文字以上","schema_trop_court":"4点以上を接続","verrou_cree":"ロックが作成されました","verrou_supprime":"ロックが削除されました","langue_changee":"言語が変更されました","rechercher_langue":"言語を検索...","non_defini":"未定義","non_renseigne":"未入力"},"lock":{"titre":"Syleaはロックされています","mdp_placeholder":"パスワードを入力...","schema_instruction":"パターンを描いてください","erreur":"パスワードまたはパターンが正しくありません","deverrouiller":"ロック解除"}},
  zh: {"nav":{"dashboard":"仪表板","analyser":"分析选择","statistiques":"统计","parametres":"设置","parametres_desc":"语言、安全、档案","aide":"帮助与资源","aide_desc":"即将推出","service":"客户服务","service_desc":"与助手聊天","profil_edit":"编辑个人资料","profil_create":"创建个人资料","profil_edit_desc":"更新信息","profil_create_desc":"开始你的旅程"},"settings":{"title":"设置","subtitle":"自定义你的Sylea体验","profil":"我的资料","profil_desc":"查看个人信息","langue":"语言","langue_desc":"选择应用语言","securite":"安全","securite_desc":"保护你的个人数据","archives":"决策档案","archives_desc":"查找所有过去的决策","identite":"身份","objectif":"人生目标","competences":"技能","diplomes":"学历","langues":"语言","bien_etre":"幸福感","repartition_temps":"时间分配","genre":"性别","nom":"姓名","age":"年龄","profession":"职业","ville":"城市","situation":"家庭状况","categorie":"类别","deadline":"截止日期","probabilite":"当前概率","sante":"健康","stress":"压力","energie":"精力","bonheur":"幸福","travail":"工作","sommeil":"睡眠","loisirs":"休闲","transport":"交通","objectif_h":"目标","h_jour":"小时/天","ans":"岁","rechercher":"搜索决策...","tri_recent":"最新","tri_ancien":"最旧","tri_impact":"按影响","aucune_decision":"未找到决策","impact":"影响","choix":"选择","date":"日期","page":"页","sur":"共","securite_niveau":"安全级别","aucun_verrou":"无锁定","mot_de_passe":"密码","schema":"图案锁","creer_mdp":"创建密码","creer_schema":"绘制图案","confirmer_mdp":"确认密码","confirmer_schema":"确认图案","supprimer_verrou":"移除锁定","verrou_actif":"锁定已启用","mdp_placeholder":"输入密码...","mdp_confirmer_placeholder":"确认密码...","mdp_mismatch":"密码不匹配","mdp_trop_court":"至少4个字符","schema_trop_court":"至少连接4个点","verrou_cree":"锁定创建成功","verrou_supprime":"锁定已移除","langue_changee":"语言已更改","rechercher_langue":"搜索语言...","non_defini":"未定义","non_renseigne":"未提供"},"lock":{"titre":"Sylea已锁定","mdp_placeholder":"输入密码...","schema_instruction":"绘制你的图案","erreur":"密码或图案不正确","deverrouiller":"解锁"}},
  ko: {"nav":{"dashboard":"대시보드","analyser":"선택 분석","statistiques":"통계","parametres":"설정","parametres_desc":"언어, 보안, 아카이브","aide":"도움말","aide_desc":"곧 제공","service":"고객 서비스","service_desc":"어시스턴트와 채팅","profil_edit":"프로필 편집","profil_create":"프로필 생성","profil_edit_desc":"정보 업데이트","profil_create_desc":"여정을 시작하세요"},"settings":{"title":"설정","subtitle":"Sylea 경험을 맞춤 설정","profil":"내 프로필","profil_desc":"개인 정보 보기","langue":"언어","langue_desc":"앱 언어 선택","securite":"보안","securite_desc":"개인 데이터 보호","archives":"결정 아카이브","archives_desc":"과거 결정 검색","identite":"신원","objectif":"인생 목표","competences":"역량","diplomes":"학위","langues":"언어","bien_etre":"웰빙","repartition_temps":"시간 배분","genre":"성별","nom":"이름","age":"나이","profession":"직업","ville":"도시","situation":"가족 상황","categorie":"카테고리","deadline":"기한","probabilite":"현재 확률","sante":"건강","stress":"스트레스","energie":"에너지","bonheur":"행복","travail":"업무","sommeil":"수면","loisirs":"여가","transport":"교통","objectif_h":"목표","h_jour":"시간/일","ans":"세","rechercher":"결정 검색...","tri_recent":"최신순","tri_ancien":"오래된순","tri_impact":"영향순","aucune_decision":"결정을 찾을 수 없습니다","impact":"영향","choix":"선택","date":"날짜","page":"페이지","sur":"중","securite_niveau":"보안 수준","aucun_verrou":"잠금 없음","mot_de_passe":"비밀번호","schema":"패턴 잠금","creer_mdp":"비밀번호 생성","creer_schema":"패턴 그리기","confirmer_mdp":"비밀번호 확인","confirmer_schema":"패턴 확인","supprimer_verrou":"잠금 해제","verrou_actif":"잠금 활성화","mdp_placeholder":"비밀번호 입력...","mdp_confirmer_placeholder":"비밀번호 확인...","mdp_mismatch":"비밀번호가 일치하지 않습니다","mdp_trop_court":"최소 4자","schema_trop_court":"최소 4개 점 연결","verrou_cree":"잠금이 생성되었습니다","verrou_supprime":"잠금이 제거되었습니다","langue_changee":"언어가 변경되었습니다","rechercher_langue":"언어 검색...","non_defini":"미정의","non_renseigne":"미입력"},"lock":{"titre":"Sylea가 잠겨 있습니다","mdp_placeholder":"비밀번호 입력...","schema_instruction":"패턴을 그려주세요","erreur":"잘못된 비밀번호 또는 패턴","deverrouiller":"잠금 해제"}},
  ar: {"nav":{"dashboard":"لوحة التحكم","analyser":"تحليل اختيار","statistiques":"الإحصائيات","parametres":"الإعدادات","parametres_desc":"اللغة، الأمان، الأرشيف","aide":"المساعدة والموارد","aide_desc":"قريباً","service":"خدمة العملاء","service_desc":"تحدث مع مساعدنا","profil_edit":"تعديل الملف الشخصي","profil_create":"إنشاء ملف شخصي","profil_edit_desc":"تحديث المعلومات","profil_create_desc":"ابدأ رحلتك"},"settings":{"title":"الإعدادات","subtitle":"خصص تجربة Sylea الخاصة بك","profil":"ملفي الشخصي","profil_desc":"عرض المعلومات الشخصية","langue":"اللغة","langue_desc":"اختر لغة التطبيق","securite":"الأمان","securite_desc":"حماية بياناتك الشخصية","archives":"أرشيف القرارات","archives_desc":"ابحث عن جميع قراراتك السابقة","identite":"الهوية","objectif":"هدف الحياة","competences":"المهارات","diplomes":"الشهادات","langues":"اللغات","bien_etre":"الرفاهية","repartition_temps":"توزيع الوقت","genre":"الجنس","nom":"الاسم","age":"العمر","profession":"المهنة","ville":"المدينة","situation":"الحالة العائلية","categorie":"الفئة","deadline":"الموعد النهائي","probabilite":"الاحتمال الحالي","sante":"الصحة","stress":"التوتر","energie":"الطاقة","bonheur":"السعادة","travail":"العمل","sommeil":"النوم","loisirs":"الترفيه","transport":"النقل","objectif_h":"الهدف","h_jour":"ساعة/يوم","ans":"سنة","rechercher":"البحث عن قرار...","tri_recent":"الأحدث","tri_ancien":"الأقدم","tri_impact":"حسب التأثير","aucune_decision":"لم يتم العثور على قرارات","impact":"التأثير","choix":"الاختيار","date":"التاريخ","page":"الصفحة","sur":"من","securite_niveau":"مستوى الأمان","aucun_verrou":"بدون قفل","mot_de_passe":"كلمة المرور","schema":"نمط القفل","creer_mdp":"إنشاء كلمة مرور","creer_schema":"رسم نمط","confirmer_mdp":"تأكيد كلمة المرور","confirmer_schema":"تأكيد النمط","supprimer_verrou":"إزالة القفل","verrou_actif":"القفل مفعل","mdp_placeholder":"أدخل كلمة المرور...","mdp_confirmer_placeholder":"أكد كلمة المرور...","mdp_mismatch":"كلمات المرور غير متطابقة","mdp_trop_court":"4 أحرف على الأقل","schema_trop_court":"قم بتوصيل 4 نقاط على الأقل","verrou_cree":"تم إنشاء القفل بنجاح","verrou_supprime":"تم إزالة القفل","langue_changee":"تم تغيير اللغة","rechercher_langue":"البحث عن لغة...","non_defini":"غير محدد","non_renseigne":"غير مقدم"},"lock":{"titre":"Sylea مقفلة","mdp_placeholder":"أدخل كلمة المرور...","schema_instruction":"ارسم النمط الخاص بك","erreur":"كلمة مرور أو نمط غير صحيح","deverrouiller":"فتح القفل"}},
  hi: {"nav":{"dashboard":"डैशबोर्ड","analyser":"विकल्प का विश्लेषण","statistiques":"आंकड़े","parametres":"सेटिंग्स","parametres_desc":"भाषा, सुरक्षा, अभिलेख","aide":"सहायता","aide_desc":"जल्द आ रहा है","service":"ग्राहक सेवा","service_desc":"हमारे सहायक से चैट करें","profil_edit":"प्रोफ़ाइल संपादित करें","profil_create":"प्रोफ़ाइल बनाएं","profil_edit_desc":"जानकारी अपडेट करें","profil_create_desc":"अपनी यात्रा शुरू करें"},"settings":{"title":"सेटिंग्स","subtitle":"अपना Sylea अनुभव अनुकूलित करें","profil":"मेरी प्रोफ़ाइल","profil_desc":"व्यक्तिगत जानकारी देखें","langue":"भाषा","langue_desc":"ऐप की भाषा चुनें","securite":"सुरक्षा","securite_desc":"अपने व्यक्तिगत डेटा की रक्षा करें","archives":"निर्णय अभिलेख","archives_desc":"अपने सभी पिछले निर्णय खोजें","identite":"पहचान","objectif":"जीवन का लक्ष्य","competences":"कौशल","diplomes":"डिग्री","langues":"भाषाएं","bien_etre":"कल्याण","repartition_temps":"समय वितरण","genre":"लिंग","nom":"नाम","age":"उम्र","profession":"पेशा","ville":"शहर","situation":"पारिवारिक स्थिति","categorie":"श्रेणी","deadline":"समय सीमा","probabilite":"वर्तमान संभावना","sante":"स्वास्थ्य","stress":"तनाव","energie":"ऊर्जा","bonheur":"खुशी","travail":"काम","sommeil":"नींद","loisirs":"मनोरंजन","transport":"परिवहन","objectif_h":"लक्ष्य","h_jour":"घंटे/दिन","ans":"वर्ष","rechercher":"निर्णय खोजें...","tri_recent":"नवीनतम","tri_ancien":"पुराने","tri_impact":"प्रभाव के अनुसार","aucune_decision":"कोई निर्णय नहीं मिला","impact":"प्रभाव","choix":"चयन","date":"तारीख","page":"पृष्ठ","sur":"में से","securite_niveau":"सुरक्षा स्तर","aucun_verrou":"कोई लॉक नहीं","mot_de_passe":"पासवर्ड","schema":"पैटर्न लॉक","creer_mdp":"पासवर्ड बनाएं","creer_schema":"पैटर्न बनाएं","confirmer_mdp":"पासवर्ड की पुष्टि करें","confirmer_schema":"पैटर्न की पुष्टि करें","supprimer_verrou":"लॉक हटाएं","verrou_actif":"लॉक सक्रिय","mdp_placeholder":"पासवर्ड दर्ज करें...","mdp_confirmer_placeholder":"पासवर्ड की पुष्टि करें...","mdp_mismatch":"पासवर्ड मेल नहीं खाते","mdp_trop_court":"कम से कम 4 अक्षर","schema_trop_court":"कम से कम 4 बिंदु जोड़ें","verrou_cree":"लॉक सफलतापूर्वक बनाया गया","verrou_supprime":"लॉक हटाया गया","langue_changee":"भाषा बदली गई","rechercher_langue":"भाषा खोजें...","non_defini":"अपरिभाषित","non_renseigne":"प्रदान नहीं किया गया"},"lock":{"titre":"Sylea लॉक है","mdp_placeholder":"पासवर्ड दर्ज करें...","schema_instruction":"अपना पैटर्न बनाएं","erreur":"गलत पासवर्ड या पैटर्न","deverrouiller":"अनलॉक करें"}},
  tr: {"nav":{"dashboard":"Kontrol Paneli","analyser":"Secim analizi","statistiques":"Istatistikler","parametres":"Ayarlar","parametres_desc":"Dil, guvenlik, arsiv","aide":"Yardim","aide_desc":"Yakinda","service":"Musteri hizmeti","service_desc":"Asistanimizla sohbet edin","profil_edit":"Profili duzenle","profil_create":"Profil olustur","profil_edit_desc":"Bilgileri guncelle","profil_create_desc":"Yolculugunuza baslayin"},"settings":{"title":"Ayarlar","subtitle":"Sylea deneyiminizi ozellestirin","profil":"Profilim","profil_desc":"Kisisel bilgileri goruntule","langue":"Dil","langue_desc":"Uygulama dilini secin","securite":"Guvenlik","securite_desc":"Kisisel verilerinizi koruyun","archives":"Karar arsivi","archives_desc":"Tum gecmis kararlarinizi bulun","identite":"Kimlik","objectif":"Yasam hedefi","competences":"Yetkinlikler","diplomes":"Diplomalar","langues":"Diller","bien_etre":"Refah","repartition_temps":"Zaman dagilimi","genre":"Cinsiyet","nom":"Isim","age":"Yas","profession":"Meslek","ville":"Sehir","situation":"Aile durumu","categorie":"Kategori","deadline":"Son tarih","probabilite":"Mevcut olasilik","sante":"Saglik","stress":"Stres","energie":"Enerji","bonheur":"Mutluluk","travail":"Is","sommeil":"Uyku","loisirs":"Bos zaman","transport":"Ulasim","objectif_h":"Hedef","h_jour":"saat/gun","ans":"yas","rechercher":"Karar ara...","tri_recent":"En yeni","tri_ancien":"En eski","tri_impact":"Etkiye gore","aucune_decision":"Karar bulunamadi","impact":"Etki","choix":"Secim","date":"Tarih","page":"Sayfa","sur":"toplam","securite_niveau":"Guvenlik seviyesi","aucun_verrou":"Kilit yok","mot_de_passe":"Sifre","schema":"Desen kilidi","creer_mdp":"Sifre olustur","creer_schema":"Desen ciz","confirmer_mdp":"Sifreyi onayla","confirmer_schema":"Deseni onayla","supprimer_verrou":"Kilidi kaldir","verrou_actif":"Kilit aktif","mdp_placeholder":"Sifrenizi girin...","mdp_confirmer_placeholder":"Sifrenizi onaylayin...","mdp_mismatch":"Sifreler uyusmuyor","mdp_trop_court":"En az 4 karakter","schema_trop_court":"En az 4 noktayi baglayin","verrou_cree":"Kilit basariyla olusturuldu","verrou_supprime":"Kilit kaldirildi","langue_changee":"Dil degistirildi","rechercher_langue":"Dil ara...","non_defini":"Tanimlanmamis","non_renseigne":"Belirtilmemis"},"lock":{"titre":"Sylea kilitli","mdp_placeholder":"Sifrenizi girin...","schema_instruction":"Deseninizi cizin","erreur":"Yanlis sifre veya desen","deverrouiller":"Kilidi ac"}},
  nl: {"nav":{"dashboard":"Dashboard","analyser":"Keuze analyseren","statistiques":"Statistieken","parametres":"Instellingen","parametres_desc":"Taal, beveiliging, archief","aide":"Help & bronnen","aide_desc":"Binnenkort beschikbaar","service":"Klantenservice","service_desc":"Chat met onze assistent","profil_edit":"Profiel bewerken","profil_create":"Profiel aanmaken","profil_edit_desc":"Informatie bijwerken","profil_create_desc":"Begin je reis"},"settings":{"title":"Instellingen","subtitle":"Pas je Sylea-ervaring aan","profil":"Mijn profiel","profil_desc":"Bekijk persoonlijke informatie","langue":"Taal","langue_desc":"Kies de app-taal","securite":"Beveiliging","securite_desc":"Bescherm je persoonlijke gegevens","archives":"Beslissingsarchief","archives_desc":"Vind al je eerdere beslissingen","identite":"Identiteit","objectif":"Levensdoel","competences":"Vaardigheden","diplomes":"Diploma's","langues":"Talen","bien_etre":"Welzijn","repartition_temps":"Tijdsverdeling","genre":"Geslacht","nom":"Naam","age":"Leeftijd","profession":"Beroep","ville":"Stad","situation":"Gezinssituatie","categorie":"Categorie","deadline":"Deadline","probabilite":"Huidige kans","sante":"Gezondheid","stress":"Stress","energie":"Energie","bonheur":"Geluk","travail":"Werk","sommeil":"Slaap","loisirs":"Vrije tijd","transport":"Vervoer","objectif_h":"Doel","h_jour":"u/dag","ans":"jaar","rechercher":"Beslissing zoeken...","tri_recent":"Nieuwste","tri_ancien":"Oudste","tri_impact":"Op impact","aucune_decision":"Geen beslissing gevonden","impact":"Impact","choix":"Keuze","date":"Datum","page":"Pagina","sur":"van","securite_niveau":"Beveiligingsniveau","aucun_verrou":"Geen vergrendeling","mot_de_passe":"Wachtwoord","schema":"Patroonvergrendeling","creer_mdp":"Wachtwoord aanmaken","creer_schema":"Patroon tekenen","confirmer_mdp":"Wachtwoord bevestigen","confirmer_schema":"Patroon bevestigen","supprimer_verrou":"Vergrendeling verwijderen","verrou_actif":"Vergrendeling actief","mdp_placeholder":"Wachtwoord invoeren...","mdp_confirmer_placeholder":"Wachtwoord bevestigen...","mdp_mismatch":"Wachtwoorden komen niet overeen","mdp_trop_court":"Minimaal 4 tekens","schema_trop_court":"Verbind minimaal 4 punten","verrou_cree":"Vergrendeling aangemaakt","verrou_supprime":"Vergrendeling verwijderd","langue_changee":"Taal gewijzigd","rechercher_langue":"Taal zoeken...","non_defini":"Niet gedefinieerd","non_renseigne":"Niet opgegeven"},"lock":{"titre":"Sylea is vergrendeld","mdp_placeholder":"Wachtwoord invoeren...","schema_instruction":"Teken je patroon","erreur":"Onjuist wachtwoord of patroon","deverrouiller":"Ontgrendelen"}},
  pl: {"nav":{"dashboard":"Panel","analyser":"Analiza wyboru","statistiques":"Statystyki","parametres":"Ustawienia","parametres_desc":"Jezyk, bezpieczenstwo, archiwum","aide":"Pomoc","aide_desc":"Wkrotce","service":"Obsluga klienta","service_desc":"Porozmawiaj z asystentem","profil_edit":"Edytuj profil","profil_create":"Utworz profil","profil_edit_desc":"Zaktualizuj informacje","profil_create_desc":"Rozpocznij podroz"},"settings":{"title":"Ustawienia","subtitle":"Dostosuj swoje doswiadczenie Sylea","profil":"Moj profil","profil_desc":"Wyswietl dane osobowe","langue":"Jezyk","langue_desc":"Wybierz jezyk aplikacji","securite":"Bezpieczenstwo","securite_desc":"Chron swoje dane osobowe","archives":"Archiwum decyzji","archives_desc":"Znajdz wszystkie poprzednie decyzje","identite":"Tozsamosc","objectif":"Cel zyciowy","competences":"Kompetencje","diplomes":"Dyplomy","langues":"Jezyki","bien_etre":"Dobrostan","repartition_temps":"Podzial czasu","genre":"Plec","nom":"Imie","age":"Wiek","profession":"Zawod","ville":"Miasto","situation":"Status rodzinny","categorie":"Kategoria","deadline":"Termin","probabilite":"Aktualne prawdopodobienstwo","sante":"Zdrowie","stress":"Stres","energie":"Energia","bonheur":"Szczescie","travail":"Praca","sommeil":"Sen","loisirs":"Czas wolny","transport":"Transport","objectif_h":"Cel","h_jour":"godz/dzien","ans":"lat","rechercher":"Szukaj decyzji...","tri_recent":"Najnowsze","tri_ancien":"Najstarsze","tri_impact":"Wedlug wplywu","aucune_decision":"Nie znaleziono decyzji","impact":"Wplyw","choix":"Wybor","date":"Data","page":"Strona","sur":"z","securite_niveau":"Poziom bezpieczenstwa","aucun_verrou":"Brak blokady","mot_de_passe":"Haslo","schema":"Wzor blokady","creer_mdp":"Utworz haslo","creer_schema":"Narysuj wzor","confirmer_mdp":"Potwierdz haslo","confirmer_schema":"Potwierdz wzor","supprimer_verrou":"Usun blokade","verrou_actif":"Blokada aktywna","mdp_placeholder":"Wprowadz haslo...","mdp_confirmer_placeholder":"Potwierdz haslo...","mdp_mismatch":"Hasla nie pasuja","mdp_trop_court":"Minimum 4 znaki","schema_trop_court":"Polacz co najmniej 4 punkty","verrou_cree":"Blokada utworzona","verrou_supprime":"Blokada usunieta","langue_changee":"Jezyk zmieniony","rechercher_langue":"Szukaj jezyka...","non_defini":"Nieokreslone","non_renseigne":"Nie podano"},"lock":{"titre":"Sylea jest zablokowana","mdp_placeholder":"Wprowadz haslo...","schema_instruction":"Narysuj swoj wzor","erreur":"Nieprawidlowe haslo lub wzor","deverrouiller":"Odblokuj"}},
  sv: {"nav":{"dashboard":"Instrumentpanel","analyser":"Analysera val","statistiques":"Statistik","parametres":"Installningar","parametres_desc":"Sprak, sakerhet, arkiv","aide":"Hjalp","aide_desc":"Kommer snart","service":"Kundtjanst","service_desc":"Chatta med var assistent","profil_edit":"Redigera profil","profil_create":"Skapa profil","profil_edit_desc":"Uppdatera information","profil_create_desc":"Borja din resa"},"settings":{"title":"Installningar","subtitle":"Anpassa din Sylea-upplevelse","profil":"Min profil","profil_desc":"Visa personlig information","langue":"Sprak","langue_desc":"Valj appsprak","securite":"Sakerhet","securite_desc":"Skydda dina personuppgifter","archives":"Beslutsarkiv","archives_desc":"Hitta alla tidigare beslut","identite":"Identitet","objectif":"Livsmal","competences":"Kompetenser","diplomes":"Examina","langues":"Sprak","bien_etre":"Valbefinnande","repartition_temps":"Tidsfordelning","genre":"Kon","nom":"Namn","age":"Alder","profession":"Yrke","ville":"Stad","situation":"Familjestatus","categorie":"Kategori","deadline":"Deadline","probabilite":"Aktuell sannolikhet","sante":"Halsa","stress":"Stress","energie":"Energi","bonheur":"Lycka","travail":"Arbete","sommeil":"Somn","loisirs":"Fritid","transport":"Transport","objectif_h":"Mal","h_jour":"tim/dag","ans":"ar","rechercher":"Sok beslut...","tri_recent":"Nyaste","tri_ancien":"Aldsta","tri_impact":"Efter paverkan","aucune_decision":"Inga beslut hittades","impact":"Paverkan","choix":"Val","date":"Datum","page":"Sida","sur":"av","securite_niveau":"Sakerhetsniva","aucun_verrou":"Inget las","mot_de_passe":"Losenord","schema":"Monsterlas","creer_mdp":"Skapa losenord","creer_schema":"Rita monster","confirmer_mdp":"Bekrafta losenord","confirmer_schema":"Bekrafta monster","supprimer_verrou":"Ta bort las","verrou_actif":"Las aktivt","mdp_placeholder":"Ange losenord...","mdp_confirmer_placeholder":"Bekrafta losenord...","mdp_mismatch":"Losenorden matchar inte","mdp_trop_court":"Minst 4 tecken","schema_trop_court":"Koppla minst 4 punkter","verrou_cree":"Las skapat","verrou_supprime":"Las borttaget","langue_changee":"Sprak andrat","rechercher_langue":"Sok sprak...","non_defini":"Odefinierat","non_renseigne":"Ej angivet"},"lock":{"titre":"Sylea ar last","mdp_placeholder":"Ange losenord...","schema_instruction":"Rita ditt monster","erreur":"Fel losenord eller monster","deverrouiller":"Las upp"}},
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState(() =>
    localStorage.getItem('sylea-lang') || 'fr'
  )
  const [translations, setTranslations] = useState<Translations>(frJson as Translations)

  // Load translations for a given locale
  const loadTranslations = useCallback(async (code: string) => {
    // 1. Check JSON file loaders (fr, en, en-US)
    const loader = localeLoaders[code]
    if (loader) {
      try {
        const mod = await loader()
        setTranslations(mod.default as Translations)
        return
      } catch { /* fall through */ }
    }
    // 2. Check embedded translations
    const embedded = embeddedTranslations[code]
    if (embedded) {
      setTranslations(embedded)
      return
    }
    // 3. Fallback to French
    setTranslations(frJson as Translations)
  }, [])

  useEffect(() => {
    loadTranslations(locale)
  }, [locale, loadTranslations])

  const setLocale = useCallback((code: string) => {
    localStorage.setItem('sylea-lang', code)
    setLocaleState(code)
  }, [])

  const t = useCallback((key: string) => lookup(translations, key), [translations])

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
